### ISSUE TITLE
Profiler possibly ticking inactive chunks again?

### ISSUE THREAD

**Issue by Cozza38** [nallar/TickProfiler#17]
Hi Nallar,

I was messing around with aperf tonight and noticed it was printing TE locations for what should have been inactive chunks. 

Is it possible that inactive chunks are being ticked again since the change to cauldron? I can't remember the process we used to test that inactive chunks were being ticked.

Currently using Cauldron Build #60

**Comment by LunNova** [comment]
@Cozza38 I wasn't able to replicate the issue initially, but during recent re-engineering fixed a possible cause.

Can you confirm if it's still a problem on new builds?

**Comment by CoryManson** [comment]
Hi mate,

I'm not doing much in the MC space anymore but I've pinged my staff team to take a look

**Comment by LunNova** [comment]
That's fine :) I'll close it given the lack of response as it should be fixed after that change.

Sorry if I incorrectly closed it originally.
