### ISSUE TITLE
Packet profiling

### ISSUE THREAD

**Issue by Slind14** [nallar/TickProfiler#22]
Hey,
what was the command for the network profiling again? The tickthreading issues and the wiki got closed so I'm not able to look it up there.

**Comment by LunNova** [comment]
Partially implemented in 616fb949ea2e

It currently only works for detecting packets sent to clients who connect to your client while it's in LAN mode. Not very useful!

**Comment by LunNova** [comment]
Actually it might work fine, will test shortly.

**Comment by LunNova** [comment]
Seems fine here, assuming fixed.

**Comment by Slind14** [comment]
ahh cool, will there be a backport to 1.7.10? Not really sure how to understand it being on 1.10 branch but noting thermos in the description.
